### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by mhshoara** [karask/python-bitcoin-utils#62]
I tried to run this code : 
https://github.com/karask/python-bitcoin-utils/blob/master/examples/spend_p2tr_default_path.py
I got tihs TypeError : 
Traceback (most recent call last):
  File "bitcoin.py", line 14, in <module>
    from bitcoinutils.transactions import Transaction, TxInput, TxOutput, TxWitnessInput
  File "/home/mhshoara/.local/lib/python3.8/site-packages/bitcoinutils/transactions.py", line 35, in <module>
    from bitcoinutils.script import Script
  File "/home/mhshoara/.local/lib/python3.8/site-packages/bitcoinutils/script.py", line 233, in <module>
    class Script:
  File "/home/mhshoara/.local/lib/python3.8/site-packages/bitcoinutils/script.py", line 272, in Script
    def __init__(self, script: list[Any]):
TypeError: 'type' object is not subscriptable

How can I solve this problem ?

**Comment by karask** [comment]
Hi @mhshoara,

You need python 3.10 and above for the typing to work. I updated the readme accordingly. Thanks for the feedback.
